/* Auto-generated by midi2sound_macrotime.py */
/* TIME is emitted as macro expressions (T04_, T08_+(T08_/2), ..., TIT_) from Sound.h */
/* Source BPM used for scaling: 264.000 */
SOUND_T ccnt2[] = {
    {MI1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {DO0_, T16_},
    {RST_, TIT_ + T32_},
    {MI1_, T16_},
    {RST_, TIT_ + T32_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {RST_, TIT_ + T32_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, T16_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {DO1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {DO0_, T16_},
    {RST_, TIT_ + T32_},
    {DO1_, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, T16_},
    {RST_, TIT_ + T32_},
    {RE0s, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, T16_},
    {RST_, TIT_ + T32_},
    {SO0_, T16_},
    {RA0s, T16_},
    {RST_, TIT_ + T32_},
    {MI1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {DO0_, T16_},
    {RST_, TIT_ + T32_},
    {MI1_, T16_},
    {RST_, TIT_ + T32_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {RST_, TIT_ + T32_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, T16_},
    {RE1_, T16_},
    {RST_, TIT_ + T32_},
    {DO1_, T16_},
    {RST_, TIT_ + T32_},
    {FA0_, T16_},
    {DO0_, T16_},
    {RST_, TIT_ + T32_ + T08_ + T02_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T04_},
    {DO1_, T16_},
    {DO1s, T16_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {RA0s, T16_},
    {SI0_, T16_},
    {DO1_, TIT_ + T32_ + T08_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T16_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_ + (T16_/2)},
    {RST_, T32_ + T04_ + (T04_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, T16_},
    {RA0s, T16_},
    {SO0s, T16_},
    {FA0s, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, T16_},
    {RA0s, T16_},
    {SO0s, T16_},
    {FA0s, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T04_},
    {SO0s, T32_},
    {SO0_, T32_},
    {FA0s, T32_},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, T16_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, T16_ + (T16_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {SO0s, TIT_ + T16_},
    {RST_, TIT_},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, T16_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, T16_ + (T16_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {SO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, T16_},
    {RE1_, T16_},
    {RE1s, T16_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_ + T08_},
    {RE1_, TIT_ + T32_ + T08_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {SO0s, T16_ + (T16_/2)},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {MI0_, T16_},
    {FA0s, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, TIT_ + T16_},
    {RST_, TIT_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {RA0_, TIT_ + T16_},
    {RST_, TIT_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T16_},
    {RE1s, T16_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, T08_ + (T08_/2)},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, T32_},
    {FA1_, T32_},
    {RE1s, T32_},
    {DO1_, T16_},
    {RE1s, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, TIT_ + T16_ + (T16_/2)},
    {RE0s, T16_},
    {RA0s, T16_},
    {RA0_, T16_},
    {RA0s, T32_},
    {SI0_, T32_},
    {DO1_, T32_},
    {RE1_, T32_},
    {RE1s, T32_},
    {MI1_, T32_},
    {FA1_, T32_ + T08_ + T02_ + (T02_/2)},
    {RST_, T32_ + T08_ + (T08_/2)},
    {SI0_, TIT_ + T32_ + T08_ + (T08_/2)},
    {SI0_, T32_ + T08_},
    {DO1_, T32_ + T08_},
    {DO1s, T32_ + T08_},
    {DO1_, T32_},
    {RE1_, T16_ + T04_},
    {RA0s, TIT_ + T16_ + (T16_/2)},
    {RE1_, TIT_ + T16_ + T04_ + (T04_/2)},
    {RST_, TIT_ + T16_ + T04_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, T32_ + T08_},
    {RE1_, T32_ + T08_},
    {RE1s, T32_ + T08_},
    {RE1_, T32_},
    {MI1_, T16_ + T04_},
    {DO1_, TIT_ + T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_ + T04_ + (T04_/2)},
    {RST_, TIT_ + T16_ + T04_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T32_ + T08_},
    {MI1_, T32_ + T08_},
    {FA1_, T32_ + T08_},
    {RA1_, T16_},
    {RST_, T32_ + T08_},
    {RA1_, T16_},
    {RST_, T16_ + (T16_/2)},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, TIT_ + T16_},
    {RST_, T16_},
    {SO1_, T16_},
    {RST_, T32_ + T08_},
    {FA1_, T16_},
    {RST_, T32_ + T08_},
    {FA1_, T16_},
    {RST_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, T16_},
    {MI1_, T16_},
    {RST_, T32_ + T08_},
    {DO2_, T16_},
    {RST_, T32_ + T08_},
    {DO2_, T16_},
    {RST_, T16_ + (T16_/2)},
    {RA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1s, TIT_ + T16_},
    {RST_, T16_},
    {RA1s, T16_},
    {RST_, T32_ + T08_},
    {SO1s, T16_},
    {RST_, T32_ + T08_},
    {SO1s, T16_},
    {RST_, T16_ + (T16_/2)},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, T16_},
    {FA1s, T16_},
    {RST_, T00_},
    {RST_, T16_},
    {DO1_, TIT_ + T16_},
    {DO1s, T32_},
    {RE1_, TIT_ + T16_},
    {DO1s, T32_},
    {DO1_, TIT_ + T16_},
    {DO1s, T32_},
    {RE1_, TIT_ + T16_},
    {DO1s, T32_},
    {DO1_, T32_},
    {RE1_, T32_},
    {RE1s, T32_},
    {MI1_, T32_},
    {FA1_, T32_},
    {FA1s, T32_},
    {SO0_, T32_},
    {SO0s, T32_},
    {RA0_, T32_},
    {RA0s, T32_},
    {SI0_, T32_},
    {DO1_, T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T04_},
    {DO1_, T16_},
    {DO1s, T16_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {RA0s, T16_},
    {SI0_, T16_},
    {DO1_, TIT_ + T32_ + T08_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T16_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_ + (T16_/2)},
    {RST_, T32_ + T04_ + (T04_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, T16_},
    {RA0s, T16_},
    {SO0s, T16_},
    {FA0s, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, T16_},
    {RA0s, T16_},
    {SO0s, T16_},
    {FA0s, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T04_},
    {SO0s, T32_},
    {SO0_, T32_},
    {FA0s, T32_},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, T16_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, T16_ + (T16_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {SO0s, TIT_ + T16_},
    {RST_, TIT_},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, T16_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, T16_ + (T16_/2)},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {SO1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1s, T16_},
    {RE1_, T16_},
    {RE1s, T16_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_ + T08_},
    {RE1_, TIT_ + T32_ + T08_},
    {DO1s, TIT_ + T16_},
    {RST_, TIT_},
    {SI0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {SO0s, T16_ + (T16_/2)},
    {MI0_, TIT_ + T16_},
    {RST_, TIT_},
    {MI0_, T16_},
    {FA0s, TIT_ + T16_},
    {RST_, TIT_},
    {SO0s, TIT_ + T16_},
    {RST_, TIT_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {RA0_, TIT_ + T16_},
    {RST_, TIT_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0_, T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T16_},
    {RE1s, T16_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, T08_ + (T08_/2)},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, T32_},
    {FA1_, T32_},
    {RE1s, T32_},
    {DO1_, T16_},
    {RE1s, T16_},
    {RST_, TIT_ + T32_},
    {RA0s, TIT_ + T16_ + (T16_/2)},
    {RE0s, T16_},
    {RA0s, T16_},
    {RA0_, T16_},
    {RA0s, T32_},
    {SI0_, T32_},
    {DO1_, T32_},
    {RE1_, T32_},
    {RE1s, T32_},
    {MI1_, T32_},
    {FA1_, T32_ + T08_ + T02_ + (T02_/2)},
    {RST_, T32_ + T08_ + (T08_/2)},
    {SI0_, TIT_ + T32_ + T08_ + (T08_/2)},
    {SI0_, T32_ + T08_},
    {DO1_, T32_ + T08_},
    {DO1s, T32_ + T08_},
    {DO1_, T32_},
    {RE1_, T16_ + T04_},
    {RA0s, TIT_ + T16_ + (T16_/2)},
    {RE1_, TIT_ + T16_ + T04_ + (T04_/2)},
    {RST_, TIT_ + T16_ + T04_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, T32_ + T08_},
    {RE1_, T32_ + T08_},
    {RE1s, T32_ + T08_},
    {RE1_, T32_},
    {MI1_, T16_ + T04_},
    {DO1_, TIT_ + T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_ + T04_ + (T04_/2)},
    {RST_, TIT_ + T16_ + T04_},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, T32_ + T08_},
    {MI1_, T32_ + T08_},
    {FA1_, T32_ + T08_},
    {RA1_, T16_},
    {RST_, T32_ + T08_},
    {RA1_, T16_},
    {RST_, T16_ + (T16_/2)},
    {SO1_, TIT_ + T16_},
    {RST_, TIT_},
    {SO1_, TIT_ + T16_},
    {RST_, T16_},
    {SO1_, T16_},
    {RST_, T32_ + T08_},
    {FA1_, T16_},
    {RST_, T32_ + T08_},
    {FA1_, T16_},
    {RST_, T16_ + (T16_/2)},
    {MI1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_},
    {RST_, T16_},
    {MI1_, T16_},
    {RST_, T32_ + T08_},
    {DO2_, T16_},
    {RST_, T32_ + T08_},
    {DO2_, T16_},
    {RST_, T16_ + (T16_/2)},
    {RA1s, TIT_ + T16_},
    {RST_, TIT_},
    {RA1s, TIT_ + T16_},
    {RST_, T16_},
    {RA1s, T16_},
    {RST_, T32_ + T08_},
    {SO1s, T16_},
    {RST_, T32_ + T08_},
    {SO1s, T16_},
    {RST_, T16_ + (T16_/2)},
    {FA1s, TIT_ + T16_},
    {RST_, TIT_},
    {FA1s, TIT_ + T16_},
    {RST_, T16_},
    {FA1s, T16_},
    {RST_, T00_},
    {RST_, T16_},
    {DO1_, TIT_ + T16_},
    {DO1s, T32_},
    {RE1_, TIT_ + T16_},
    {DO1s, T32_},
    {DO1_, TIT_ + T16_},
    {DO1s, T32_},
    {RE1_, TIT_ + T16_},
    {DO1s, T32_},
    {DO1_, T32_},
    {RE1_, T32_},
    {RE1s, T32_},
    {MI1_, T32_},
    {FA1_, T32_},
    {FA1s, T32_},
    {SO0_, T32_},
    {SO0s, T32_},
    {RA0_, T32_},
    {RA0s, T32_},
    {SI0_, T32_},
    {DO1_, T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T16_},
    {RST_, TIT_ + T16_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1s, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, TIT_ + T16_ + (T16_/2)},
    {RST_, TIT_ + T32_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {MI1_, T16_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {DO1_, TIT_ + T16_},
    {RST_, TIT_},
    {FA1_, TIT_ + T16_},
    {RST_, TIT_},
    {RE1_, TIT_ + T16_},
    {RST_, TIT_},
    {RA0s, T16_},
    {RA0_, T16_},
    {SO0_, T16_},
    {FA0_, TIT_ + T32_ + T08_},
    {STP_, T00_},
};
